### ISSUE TITLE
About refPE on sparse detectors

### ISSUE THREAD

**Issue by toyot-li** [ChenhongyiYang/WidthFormer#1]
Hi @ChenhongyiYang, thanks for your great work. May I know when will the code about StreamPETR with refPE be publicly released? Thanks.

**Comment by ChenhongyiYang** [comment]
Hi, thank you for being interested in our codebase. We have open-sourced the code for StreamPETR. For BEV transformation using WidthFormer, we will open-source it later because we need some time to clean up the codebase.

**Comment by Walteriy** [comment]
> Hi, thank you for being interested in our codebase. We have open-sourced the code for StreamPETR. For BEV transformation using WidthFormer, we will open-source it later because we need some time to clean up the codebase.

How long is the code open source?
