### ISSUE TITLE
Missing Imports and Definitions for CFFN, CFFN_v2, and CFFN_ConvNext

### ISSUE THREAD

**Issue by kotarotanahashi** [ChenhongyiYang/WidthFormer#10]
Thank you for sharing your code!

I noticed that in transformer_lib.py, the classes `CFFN`, `CFFN_v2`, `CFFN_CMT` and `CFFN_ConvNext` are used, but they are not imported, making them unusable. I searched for the definition in the repository but could not find them. Could you please add the files where these classes are defined?

Thank you for your assistance!

https://github.com/ChenhongyiYang/WidthFormer/blob/651c324506406541b301e77b22a613b1197591b5/WidthFormer/BEVDet/mmdet3d_plugin/dev/models/transformer/transformer_lib.py#L588C32-L588C36

**Comment by ChenhongyiYang** [comment]
Hi, 

Sorry, those CFFN-related stuff are from previous ideas that we tried. They are worse than the simple FFN. I have cleaned up the code to remove them. 

Thank you :)

**Comment by ChenhongyiYang** [comment]
hey, sorry plz ignore my previous reply. I have added the CFFN back. 

I am sorry for the missing imports. Currently, I cannot access the previous school machine that we used to develop the method, which means I cannot debug or test the code by myself, even if I could miss important stuff when clearing up the code.
