### ISSUE TITLE
mAP/NDS

### ISSUE THREAD

**Issue by L1bertad** [ChenhongyiYang/WidthFormer#11]
Hello author, there seems to be some differences between the code and the paper. What are the results of mAP and NDS? Have you considered making the logs and checkpoints public?

**Comment by ChenhongyiYang** [comment]
Hi, we are sorry that we cannot access the previous logs and models. We will retrain our model at some point in the future. However, the provided configs should be able to reproduce the numbers in the paper.

May I ask if you could share your training logs and environment settings? Maybe I can help with your problem :)

**Comment by L1bertad** [comment]
Thank you so much! I use 4 3090GPUs, batch_size is 8, lr is 2e-4, and weight_decay is 1e-2. The following are my training results, logs and environment.
![image](https://github.com/ChenhongyiYang/WidthFormer/assets/105352014/7ac99ec9-9a60-4ad9-8444-604a3889ac22)
[20240604_213640.log](https://github.com/user-attachments/files/15613743/20240604_213640.log)
[environment.txt](https://github.com/user-attachments/files/15613747/environment.txt)

**Comment by ChenhongyiYang** [comment]
hi,

We have fixed some bugs in the previous version; could you plz try again? I am sorry that I cannot try by myself because I do not have computing resources now  :(

**Comment by L1bertad** [comment]
I am glad to

**Comment by L1bertad** [comment]
> hi,
> 
> We have fixed some bugs in the previous version; could you plz try again? I am sorry that I cannot try by myself because I do not have computing resources now :(

Hello author, the bug you fixed can indeed enable the model to obtain similar indicators to the paper. 
Thanks！

**Comment by zwh19960817** [comment]
L1bertad， Can you send me a log of your latest experiment? I would like to refer to it. Thank you.

**Comment by L1bertad** [comment]
[widthformer.log](https://github.com/user-attachments/files/15881650/widthformer.log)
This is my experiment log, I hope it will be helpful to you.

**Comment by zwh19960817** [comment]
thank you so much

**Comment by zwh19960817** [comment]
L1bertad， Can you send me a weight(pth) of your latest experiment? I find that attention map of multiview pics cannot match. Thank you.

**Comment by czwbbbbb** [comment]
> [widthformer.log](https://github.com/user-attachments/files/15881650/widthformer.log) 这是我的实验日志，希望对您有所帮助。

Do you have the experiment log under BEVDet4D? Thank you very much
