### ISSUE TITLE
Missing FCOSAuxFlattenHead class

### ISSUE THREAD

**Issue by kotarotanahashi** [ChenhongyiYang/WidthFormer#12]
In the setting file `WidthFormer/BEVDet/work_configs/widthformer/bevdet_widthformer_r50.py`, `FCOSAuxFlattenHead `  is used, however this class cannot be found in the repo. I replace this class with `FCOSAuxFlattenHeadDev`. 
Is there another way to fix this?

Thanks

**Comment by ChenhongyiYang** [comment]
Hi, 

Yep, using `FCOSAuxFlattenHeadDev` is good. I have also updated the code to fix it. I am sorry for bugs in the code.
