### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by L1bertad** [ChenhongyiYang/WidthFormer#13]
Hello author, have you tested the delay of widthformer? The results of my test were not very good.

**Comment by ChenhongyiYang** [comment]
hi,

I tested the latency with the assumption that the camera parameters are fixed. Therefore you can pre-compute a lot of things, for example, frustum, rotation PE, and the distance PE before aggregating, 2D PE in refine transformer, BEV queries and their PEs. Those pre-computing could save a lot of latency.

**Comment by L1bertad** [comment]
> hi,
> 
> We tested the latency with the assumption that the camera parameters are fixed. Therefore you can pre-compute a lot of things, for example, frustum, rotation PE, and the distance PE before aggregating, 2D PE in refine transformer, BEV queries and their PEs. Those pre-computing could save a lot of latency.

Hello author, I implemented the precalculation myself and the resulting delay is 3.5ms. may I ask if this is normal? What else can speed up inference?
