### ISSUE TITLE
请问一下StreamPetr里面ref position encoding的代码在哪里啊？

### ISSUE THREAD

**Issue by encizhou** [ChenhongyiYang/WidthFormer#20]

**Comment by ChenhongyiYang** [comment]
Hello, 在这: https://github.com/ChenhongyiYang/WidthFormer/blob/d10ec3c6d0f7354ccaf5f0c9e24ddd742b1c1b35/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/stream_petr_head_ours.py#L387
